[package]
name = "unix-ancillary-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.unix-ancillary]
path = ".."

[[bin]]
name = "parse_cmsg"
path = "fuzz_targets/parse_cmsg.rs"
test = false
doc = false
bench = false
